version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: oa-pg
    environment:
      POSTGRES_USER: oa_admin
      POSTGRES_PASSWORD: oa_pass
      POSTGRES_DB: oa_system
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d # 初始化脚本目录
    ports:
      - "5432:5432"
    networks:
      - oa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oa_admin -d oa_system"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: oa-redis
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - oa-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  oa-network:
    name: oa-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  postgres_data:
  redis_data: