version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.10"
    volumes:
      - ../:/workspace
    command: sleep infinity
    depends_on:
      - db
    environment:
      DB_URL: postgresql://postgres:postgres@db:5432/main

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: