version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.10"
    volumes:
      - "${WORKSPACE_DIR}:/workspace:cached"
    image: "${DEVCONTAINER_NAME}:latest"
    networks:
      oa-network:
        ipv4_address: 172.18.0.100
    env_file:
      - .env # 读取环境变量
    extra_hosts:
      - "host.docker.internal:host-gateway" # 支持宿主机服务访问
    # 保持容器持续运行
    command: sleep infinity
    # 增强健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  oa-network:
    external: true
    name: oa-network